######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 13 15:13:42 2013
######################################################################

CONFIG += debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
LIBS += -lkdecore
QT += xml

HEADERS += khumandatetimeparser.h
SOURCES += khumandatetimeparser.cpp main.cpp
